export type CoverageType = 'accident_only' | 'illness_accident' | 'comprehensive' | 'wellness'
export type PaymentModel = 'reimbursement' | 'direct_payment' | 'preload_card'

export interface Plan {
  id: string
  name: string
  providerId: string
  coverageType: CoverageType
  monthlyPremiumFrom: number
  monthlyPremiumTo: number
  annualLimit: number
  excessPercentage: number
  excessMinimum: number
  waitingPeriodDays: number
  coversPreExisting: boolean
  coversHereditary: boolean
  coversDental: boolean
  coversChronic: boolean
  coversRoutineCare: boolean
  coversFuneral: boolean
  breedRestrictions: string[]
  maxClaimsPerYear: number | null
  keyFeatures: string[]
}

export interface Provider {
  id: string
  name: string
  slug: string
  logo: string
  description: string
  website: string
  affiliateLink: string
  trustRating: number
  paymentModel: PaymentModel
  hasExcessBuster: boolean
  vet24Helpline: boolean
  maxPetAge: { dog: number; cat: number }
  pros: string[]
  cons: string[]
  plans: Plan[]
}

export const providers: Provider[] = [
  {
    id: 'oneplan',
    name: 'Oneplan',
    slug: 'oneplan',
    logo: '/images/providers/oneplan.svg',
    description: 'Oneplan is one of South Africa\'s most popular pet insurance providers, known for their innovative OneCard prepaid system that lets you pay your vet directly at the point of care — no claims or reimbursements needed. They offer a range of plans from basic accident cover to comprehensive pet insurance.',
    website: 'https://www.oneplan.co.za',
    affiliateLink: 'https://www.oneplan.co.za/pet-insurance',
    trustRating: 4.2,
    paymentModel: 'preload_card',
    hasExcessBuster: true,
    vet24Helpline: true,
    maxPetAge: { dog: 9, cat: 11 },
    pros: [
      'OneCard prepaid system — pay vet upfront, no claims',
      'Excess drops from 25% to 10% after 6 months',
      'Excess Buster add-on available',
      '24/7 vet helpline included',
      'Wide range of plans for different budgets',
    ],
    cons: [
      'Age restrictions for new sign-ups (dogs 8-9 years by size)',
      'Excess starts at 25% for first 6 months',
      'Pre-existing conditions not covered',
      'Breed-specific restrictions may apply',
    ],
    plans: [
      {
        id: 'oneplan-accident',
        name: 'Accident Plan',
        providerId: 'oneplan',
        coverageType: 'accident_only',
        monthlyPremiumFrom: 80,
        monthlyPremiumTo: 150,
        annualLimit: 15000,
        excessPercentage: 25,
        excessMinimum: 0,
        waitingPeriodDays: 0,
        coversPreExisting: false,
        coversHereditary: false,
        coversDental: false,
        coversChronic: false,
        coversRoutineCare: false,
        coversFuneral: false,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Accident cover only', 'No waiting period for accidents', 'OneCard prepaid system'],
      },
      {
        id: 'oneplan-pet',
        name: 'Pet Plan',
        providerId: 'oneplan',
        coverageType: 'illness_accident',
        monthlyPremiumFrom: 200,
        monthlyPremiumTo: 350,
        annualLimit: 35000,
        excessPercentage: 25,
        excessMinimum: 0,
        waitingPeriodDays: 30,
        coversPreExisting: false,
        coversHereditary: true,
        coversDental: false,
        coversChronic: true,
        coversRoutineCare: false,
        coversFuneral: false,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Illness and accident cover', 'Hereditary conditions covered', 'Chronic conditions covered', 'OneCard prepaid system'],
      },
      {
        id: 'oneplan-pet-plus',
        name: 'Pet Plus',
        providerId: 'oneplan',
        coverageType: 'comprehensive',
        monthlyPremiumFrom: 320,
        monthlyPremiumTo: 480,
        annualLimit: 50000,
        excessPercentage: 25,
        excessMinimum: 0,
        waitingPeriodDays: 30,
        coversPreExisting: false,
        coversHereditary: true,
        coversDental: true,
        coversChronic: true,
        coversRoutineCare: false,
        coversFuneral: true,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Comprehensive cover', 'Dental included', 'Funeral cover', 'Hereditary & chronic conditions', 'OneCard prepaid system'],
      },
      {
        id: 'oneplan-pet-ultra',
        name: 'Pet Ultra',
        providerId: 'oneplan',
        coverageType: 'comprehensive',
        monthlyPremiumFrom: 430,
        monthlyPremiumTo: 567,
        annualLimit: 70000,
        excessPercentage: 25,
        excessMinimum: 0,
        waitingPeriodDays: 30,
        coversPreExisting: false,
        coversHereditary: true,
        coversDental: true,
        coversChronic: true,
        coversRoutineCare: true,
        coversFuneral: true,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Maximum cover', 'Routine care included', 'Dental included', 'Funeral cover', 'All conditions covered', 'OneCard prepaid system'],
      },
    ],
  },
  {
    id: 'dotsure',
    name: 'Dotsure',
    slug: 'dotsure',
    logo: '/images/providers/dotsure.svg',
    description: 'Dotsure is a digital-first pet insurance provider in South Africa, known for their unique "Name Your Price" feature that lets you customise your premium. They also cover exotic pets including birds, rabbits, and reptiles — making them one of the most flexible options on the market.',
    website: 'https://www.dotsure.co.za',
    affiliateLink: 'https://www.dotsure.co.za/pet-insurance',
    trustRating: 4.0,
    paymentModel: 'reimbursement',
    hasExcessBuster: false,
    vet24Helpline: true,
    maxPetAge: { dog: 10, cat: 12 },
    pros: [
      '"Name Your Price" customisable premiums',
      'Covers exotic pets (birds, rabbits, reptiles)',
      'Low excess: 10% with R200 minimum',
      '24/7 vet helpline',
      'Multiple plan tiers to choose from',
    ],
    cons: [
      'Reimbursement model — you pay vet first',
      'Pre-existing conditions excluded',
      'Claims process can take time',
    ],
    plans: [
      {
        id: 'dotsure-starter',
        name: 'Starter',
        providerId: 'dotsure',
        coverageType: 'accident_only',
        monthlyPremiumFrom: 90,
        monthlyPremiumTo: 160,
        annualLimit: 10000,
        excessPercentage: 10,
        excessMinimum: 200,
        waitingPeriodDays: 0,
        coversPreExisting: false,
        coversHereditary: false,
        coversDental: false,
        coversChronic: false,
        coversRoutineCare: false,
        coversFuneral: false,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Accident cover', 'Name Your Price toggle', 'Low excess'],
      },
      {
        id: 'dotsure-bronze',
        name: 'Bronze',
        providerId: 'dotsure',
        coverageType: 'illness_accident',
        monthlyPremiumFrom: 160,
        monthlyPremiumTo: 280,
        annualLimit: 20000,
        excessPercentage: 10,
        excessMinimum: 200,
        waitingPeriodDays: 30,
        coversPreExisting: false,
        coversHereditary: false,
        coversDental: false,
        coversChronic: false,
        coversRoutineCare: false,
        coversFuneral: false,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Illness and accident cover', 'Name Your Price toggle', 'Low excess'],
      },
      {
        id: 'dotsure-silver',
        name: 'Silver',
        providerId: 'dotsure',
        coverageType: 'illness_accident',
        monthlyPremiumFrom: 250,
        monthlyPremiumTo: 400,
        annualLimit: 40000,
        excessPercentage: 10,
        excessMinimum: 200,
        waitingPeriodDays: 30,
        coversPreExisting: false,
        coversHereditary: true,
        coversDental: false,
        coversChronic: true,
        coversRoutineCare: false,
        coversFuneral: false,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Extended illness cover', 'Hereditary conditions', 'Chronic conditions', 'Name Your Price'],
      },
      {
        id: 'dotsure-gold',
        name: 'Gold',
        providerId: 'dotsure',
        coverageType: 'comprehensive',
        monthlyPremiumFrom: 380,
        monthlyPremiumTo: 550,
        annualLimit: 60000,
        excessPercentage: 10,
        excessMinimum: 200,
        waitingPeriodDays: 30,
        coversPreExisting: false,
        coversHereditary: true,
        coversDental: true,
        coversChronic: true,
        coversRoutineCare: false,
        coversFuneral: true,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Comprehensive cover', 'Dental included', 'Funeral cover', 'Hereditary & chronic'],
      },
      {
        id: 'dotsure-platinum',
        name: 'Platinum',
        providerId: 'dotsure',
        coverageType: 'comprehensive',
        monthlyPremiumFrom: 500,
        monthlyPremiumTo: 750,
        annualLimit: 100000,
        excessPercentage: 10,
        excessMinimum: 200,
        waitingPeriodDays: 30,
        coversPreExisting: false,
        coversHereditary: true,
        coversDental: true,
        coversChronic: true,
        coversRoutineCare: true,
        coversFuneral: true,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Maximum cover', 'Routine care', 'Dental', 'Funeral', 'All conditions', 'Name Your Price'],
      },
    ],
  },
  {
    id: 'medipet',
    name: 'MediPet',
    slug: 'medipet',
    logo: '/images/providers/medipet.svg',
    description: 'MediPet stands out in the South African pet insurance market with their unique LitePlus plan that covers pre-existing conditions — the only provider to do so. They have no age limit for joining, making them a great option for older pets that other insurers won\'t cover.',
    website: 'https://www.medipet.co.za',
    affiliateLink: 'https://www.medipet.co.za',
    trustRating: 4.3,
    paymentModel: 'reimbursement',
    hasExcessBuster: true,
    vet24Helpline: true,
    maxPetAge: { dog: 99, cat: 99 },
    pros: [
      'LitePlus covers pre-existing conditions (unique in SA)',
      'No age limit for joining',
      'Benefit Booster add-on available',
      'Wide range of plans from basic to comprehensive',
      '24/7 vet helpline',
    ],
    cons: [
      'Lite plan limited to 4 claims per year',
      'Excess of 20% with R300 minimum',
      'Reimbursement model',
      'Higher excess than some competitors',
    ],
    plans: [
      {
        id: 'medipet-accident',
        name: 'Accident',
        providerId: 'medipet',
        coverageType: 'accident_only',
        monthlyPremiumFrom: 149,
        monthlyPremiumTo: 199,
        annualLimit: 15000,
        excessPercentage: 20,
        excessMinimum: 300,
        waitingPeriodDays: 0,
        coversPreExisting: false,
        coversHereditary: false,
        coversDental: false,
        coversChronic: false,
        coversRoutineCare: false,
        coversFuneral: false,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Accident cover only', 'No waiting period', 'No age limit'],
      },
      {
        id: 'medipet-lite',
        name: 'Lite',
        providerId: 'medipet',
        coverageType: 'illness_accident',
        monthlyPremiumFrom: 249,
        monthlyPremiumTo: 349,
        annualLimit: 25000,
        excessPercentage: 20,
        excessMinimum: 300,
        waitingPeriodDays: 30,
        coversPreExisting: false,
        coversHereditary: false,
        coversDental: false,
        coversChronic: false,
        coversRoutineCare: false,
        coversFuneral: false,
        breedRestrictions: [],
        maxClaimsPerYear: 4,
        keyFeatures: ['Illness and accident cover', 'Max 4 claims per year', 'No age limit'],
      },
      {
        id: 'medipet-liteplus',
        name: 'LitePlus',
        providerId: 'medipet',
        coverageType: 'illness_accident',
        monthlyPremiumFrom: 349,
        monthlyPremiumTo: 499,
        annualLimit: 35000,
        excessPercentage: 20,
        excessMinimum: 300,
        waitingPeriodDays: 30,
        coversPreExisting: true,
        coversHereditary: true,
        coversDental: false,
        coversChronic: true,
        coversRoutineCare: false,
        coversFuneral: false,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Covers pre-existing conditions', 'Hereditary conditions', 'Chronic conditions', 'No age limit'],
      },
      {
        id: 'medipet-essential',
        name: 'Essential',
        providerId: 'medipet',
        coverageType: 'comprehensive',
        monthlyPremiumFrom: 449,
        monthlyPremiumTo: 599,
        annualLimit: 50000,
        excessPercentage: 20,
        excessMinimum: 300,
        waitingPeriodDays: 30,
        coversPreExisting: false,
        coversHereditary: true,
        coversDental: true,
        coversChronic: true,
        coversRoutineCare: false,
        coversFuneral: true,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Comprehensive cover', 'Dental included', 'Funeral cover', 'Hereditary & chronic'],
      },
      {
        id: 'medipet-ultimate360',
        name: 'Ultimate360',
        providerId: 'medipet',
        coverageType: 'comprehensive',
        monthlyPremiumFrom: 599,
        monthlyPremiumTo: 799,
        annualLimit: 80000,
        excessPercentage: 20,
        excessMinimum: 300,
        waitingPeriodDays: 30,
        coversPreExisting: false,
        coversHereditary: true,
        coversDental: true,
        coversChronic: true,
        coversRoutineCare: true,
        coversFuneral: true,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Maximum cover', 'Routine care', 'Dental', 'Funeral', 'All conditions', 'Benefit Booster add-on'],
      },
    ],
  },
  {
    id: 'outsurance',
    name: 'OUTsurance',
    slug: 'outsurance',
    logo: '/images/providers/outsurance.svg',
    description: 'OUTsurance is one of South Africa\'s most trusted insurance brands, now offering pet insurance with their signature OUTbonus cash refund for claim-free years. Their Executive plan is one of the most comprehensive in SA, covering puppy classes and behavioural treatments.',
    website: 'https://www.outsurance.co.za',
    affiliateLink: 'https://www.outsurance.co.za/pet-insurance/',
    trustRating: 4.5,
    paymentModel: 'reimbursement',
    hasExcessBuster: false,
    vet24Helpline: true,
    maxPetAge: { dog: 8, cat: 10 },
    pros: [
      'OUTbonus cash refund if you don\'t claim',
      'Fixed excess (not percentage-based)',
      'Executive plan covers puppy classes & behavioural treatment',
      'Trusted, established insurance brand',
      'Advanced breed-specific underwriting',
    ],
    cons: [
      'Lower maximum age limits for sign-up',
      'Reimbursement model',
      'Pre-existing conditions not covered',
    ],
    plans: [
      {
        id: 'outsurance-accident',
        name: 'Accident',
        providerId: 'outsurance',
        coverageType: 'accident_only',
        monthlyPremiumFrom: 100,
        monthlyPremiumTo: 180,
        annualLimit: 15000,
        excessPercentage: 0,
        excessMinimum: 500,
        waitingPeriodDays: 0,
        coversPreExisting: false,
        coversHereditary: false,
        coversDental: false,
        coversChronic: false,
        coversRoutineCare: false,
        coversFuneral: false,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Accident cover', 'Fixed R500 excess', 'OUTbonus rewards'],
      },
      {
        id: 'outsurance-core',
        name: 'Core',
        providerId: 'outsurance',
        coverageType: 'illness_accident',
        monthlyPremiumFrom: 220,
        monthlyPremiumTo: 380,
        annualLimit: 30000,
        excessPercentage: 0,
        excessMinimum: 750,
        waitingPeriodDays: 30,
        coversPreExisting: false,
        coversHereditary: false,
        coversDental: false,
        coversChronic: false,
        coversRoutineCare: false,
        coversFuneral: false,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Illness and accident', 'Fixed R750 excess', 'OUTbonus rewards'],
      },
      {
        id: 'outsurance-standard',
        name: 'Standard',
        providerId: 'outsurance',
        coverageType: 'comprehensive',
        monthlyPremiumFrom: 350,
        monthlyPremiumTo: 520,
        annualLimit: 50000,
        excessPercentage: 0,
        excessMinimum: 750,
        waitingPeriodDays: 30,
        coversPreExisting: false,
        coversHereditary: true,
        coversDental: true,
        coversChronic: true,
        coversRoutineCare: false,
        coversFuneral: true,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Comprehensive cover', 'Dental', 'Funeral', 'Fixed excess', 'OUTbonus rewards'],
      },
      {
        id: 'outsurance-executive',
        name: 'Executive',
        providerId: 'outsurance',
        coverageType: 'comprehensive',
        monthlyPremiumFrom: 500,
        monthlyPremiumTo: 700,
        annualLimit: 80000,
        excessPercentage: 0,
        excessMinimum: 500,
        waitingPeriodDays: 30,
        coversPreExisting: false,
        coversHereditary: true,
        coversDental: true,
        coversChronic: true,
        coversRoutineCare: true,
        coversFuneral: true,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Maximum cover', 'Puppy classes', 'Behavioural treatment', 'Routine care', 'Lower excess', 'OUTbonus'],
      },
    ],
  },
  {
    id: 'kido',
    name: 'Kido',
    slug: 'kido',
    logo: '/images/providers/kido.svg',
    description: 'Kido Pet Insurance offers straightforward, affordable pet cover for South African pet owners. With a focus on simplicity and a 24/7 emergency helpline, Kido is a great entry-level option for pet owners looking for basic protection without the complexity.',
    website: 'https://www.kido.co.za',
    affiliateLink: 'https://www.kido.co.za',
    trustRating: 3.5,
    paymentModel: 'reimbursement',
    hasExcessBuster: false,
    vet24Helpline: true,
    maxPetAge: { dog: 8, cat: 10 },
    pros: [
      'Affordable premiums starting from R99/month',
      '24/7 emergency helpline',
      'Simple, straightforward plans',
      'Easy online sign-up',
    ],
    cons: [
      'Lower annual limits compared to competitors',
      'Limited plan options',
      'Less comprehensive cover',
    ],
    plans: [
      {
        id: 'kido-basic',
        name: 'Basic',
        providerId: 'kido',
        coverageType: 'accident_only',
        monthlyPremiumFrom: 99,
        monthlyPremiumTo: 149,
        annualLimit: 10000,
        excessPercentage: 15,
        excessMinimum: 250,
        waitingPeriodDays: 0,
        coversPreExisting: false,
        coversHereditary: false,
        coversDental: false,
        coversChronic: false,
        coversRoutineCare: false,
        coversFuneral: false,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Basic accident cover', '24/7 helpline', 'Affordable premium'],
      },
      {
        id: 'kido-standard',
        name: 'Standard',
        providerId: 'kido',
        coverageType: 'illness_accident',
        monthlyPremiumFrom: 180,
        monthlyPremiumTo: 280,
        annualLimit: 18000,
        excessPercentage: 15,
        excessMinimum: 250,
        waitingPeriodDays: 30,
        coversPreExisting: false,
        coversHereditary: false,
        coversDental: false,
        coversChronic: false,
        coversRoutineCare: false,
        coversFuneral: false,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Illness and accident cover', '24/7 helpline', 'Affordable premium'],
      },
      {
        id: 'kido-premium',
        name: 'Premium',
        providerId: 'kido',
        coverageType: 'comprehensive',
        monthlyPremiumFrom: 280,
        monthlyPremiumTo: 420,
        annualLimit: 25000,
        excessPercentage: 15,
        excessMinimum: 250,
        waitingPeriodDays: 30,
        coversPreExisting: false,
        coversHereditary: true,
        coversDental: false,
        coversChronic: true,
        coversRoutineCare: false,
        coversFuneral: false,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Comprehensive cover', 'Hereditary conditions', 'Chronic conditions', '24/7 helpline'],
      },
    ],
  },
  {
    id: '1st-for-women',
    name: '1st for Women',
    slug: '1st-for-women',
    logo: '/images/providers/1st-for-women.svg',
    description: '1st for Women Pet Insurance is positioned specifically for female pet owners in South Africa. Sharing the same underwriter as Oneplan, they offer a similar OneCard prepaid system and plan structure, with the added benefit of a brand that understands women\'s needs.',
    website: 'https://www.1stforwomen.co.za',
    affiliateLink: 'https://www.1stforwomen.co.za/pet-insurance',
    trustRating: 3.8,
    paymentModel: 'preload_card',
    hasExcessBuster: true,
    vet24Helpline: true,
    maxPetAge: { dog: 9, cat: 11 },
    pros: [
      'Same underwriter as Oneplan — proven system',
      'OneCard prepaid system',
      'Excess drops from 25% to 10% after 6 months',
      'Excess Buster add-on available',
      'Designed with women pet owners in mind',
    ],
    cons: [
      'Similar pricing to Oneplan',
      'Age restrictions for sign-up',
      'Pre-existing conditions not covered',
    ],
    plans: [
      {
        id: '1stfw-accident',
        name: 'Accident',
        providerId: '1st-for-women',
        coverageType: 'accident_only',
        monthlyPremiumFrom: 85,
        monthlyPremiumTo: 155,
        annualLimit: 15000,
        excessPercentage: 25,
        excessMinimum: 0,
        waitingPeriodDays: 0,
        coversPreExisting: false,
        coversHereditary: false,
        coversDental: false,
        coversChronic: false,
        coversRoutineCare: false,
        coversFuneral: false,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Accident cover', 'OneCard system', 'No waiting period'],
      },
      {
        id: '1stfw-comprehensive',
        name: 'Comprehensive',
        providerId: '1st-for-women',
        coverageType: 'comprehensive',
        monthlyPremiumFrom: 330,
        monthlyPremiumTo: 500,
        annualLimit: 50000,
        excessPercentage: 25,
        excessMinimum: 0,
        waitingPeriodDays: 30,
        coversPreExisting: false,
        coversHereditary: true,
        coversDental: true,
        coversChronic: true,
        coversRoutineCare: false,
        coversFuneral: true,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Comprehensive cover', 'Dental', 'Funeral', 'Hereditary & chronic', 'OneCard system'],
      },
    ],
  },
  {
    id: 'pawpaw',
    name: 'PawPaw',
    slug: 'pawpaw',
    logo: '/images/providers/pawpaw.svg',
    description: 'PawPaw is a newer entrant to the South African pet insurance market, offering fresh, modern plans designed for today\'s pet owner. As a growing provider, they aim to bring competitive pricing and a streamlined digital experience to pet insurance in SA.',
    website: 'https://www.pawpaw.co.za',
    affiliateLink: 'https://www.pawpaw.co.za',
    trustRating: 3.2,
    paymentModel: 'reimbursement',
    hasExcessBuster: false,
    vet24Helpline: false,
    maxPetAge: { dog: 8, cat: 10 },
    pros: [
      'Competitive pricing as a new entrant',
      'Modern, digital-first experience',
      'Simple sign-up process',
    ],
    cons: [
      'Newer provider — less track record',
      'Limited plan information available',
      'Smaller provider network',
    ],
    plans: [
      {
        id: 'pawpaw-basic',
        name: 'Basic',
        providerId: 'pawpaw',
        coverageType: 'accident_only',
        monthlyPremiumFrom: 89,
        monthlyPremiumTo: 149,
        annualLimit: 12000,
        excessPercentage: 15,
        excessMinimum: 200,
        waitingPeriodDays: 0,
        coversPreExisting: false,
        coversHereditary: false,
        coversDental: false,
        coversChronic: false,
        coversRoutineCare: false,
        coversFuneral: false,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Accident cover', 'Affordable entry point'],
      },
      {
        id: 'pawpaw-standard',
        name: 'Standard',
        providerId: 'pawpaw',
        coverageType: 'illness_accident',
        monthlyPremiumFrom: 189,
        monthlyPremiumTo: 299,
        annualLimit: 25000,
        excessPercentage: 15,
        excessMinimum: 200,
        waitingPeriodDays: 30,
        coversPreExisting: false,
        coversHereditary: false,
        coversDental: false,
        coversChronic: false,
        coversRoutineCare: false,
        coversFuneral: false,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Illness and accident cover', 'Digital-first claims'],
      },
      {
        id: 'pawpaw-premium',
        name: 'Premium',
        providerId: 'pawpaw',
        coverageType: 'comprehensive',
        monthlyPremiumFrom: 299,
        monthlyPremiumTo: 450,
        annualLimit: 40000,
        excessPercentage: 15,
        excessMinimum: 200,
        waitingPeriodDays: 30,
        coversPreExisting: false,
        coversHereditary: true,
        coversDental: true,
        coversChronic: true,
        coversRoutineCare: false,
        coversFuneral: false,
        breedRestrictions: [],
        maxClaimsPerYear: null,
        keyFeatures: ['Comprehensive cover', 'Dental', 'Hereditary & chronic conditions'],
      },
    ],
  },
]

export function getProviderBySlug(slug: string): Provider | undefined {
  return providers.find(p => p.slug === slug)
}

export function getAllPlans(): (Plan & { providerName: string; providerSlug: string })[] {
  return providers.flatMap(provider =>
    provider.plans.map(plan => ({
      ...plan,
      providerName: provider.name,
      providerSlug: provider.slug,
    }))
  )
}

export function getCoverageTypeLabel(type: CoverageType): string {
  const labels: Record<CoverageType, string> = {
    accident_only: 'Accident Only',
    illness_accident: 'Illness + Accident',
    comprehensive: 'Comprehensive',
    wellness: 'Wellness',
  }
  return labels[type]
}
